// *****************************************************************************
// Copyright (C) 2017 TypeFox and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

import fsExtra from 'fs-extra';
const fs = fsExtra;
import { AbstractGenerator } from './abstract-generator.js';

export class RollupGenerator extends AbstractGenerator {

    async generate(): Promise<void> {
        await this.write(this.genConfigPath, this.compileRollupConfig());
        if (!this.pck.isBrowserOnly()) {
            await this.write(this.genNodeConfigPath, this.compileNodeRollupConfig());
        }
        if (await this.shouldGenerateUserRollupConfig()) {
            await this.write(this.configPath, this.compileUserRollupConfig());
        }
    }

    protected async shouldGenerateUserRollupConfig(): Promise<boolean> {
        if (!(await fs.pathExists(this.configPath))) {
            return true;
        }
        const content = await fs.readFile(this.configPath, 'utf8');
        return content.indexOf('gen-rollup') === -1;
    }

    get configPath(): string {
        return this.pck.path('rollup.config.js');
    }

    get genConfigPath(): string {
        return this.pck.path('gen-rollup.config.cjs');
    }

    get genNodeConfigPath(): string {
        return this.pck.path('gen-rollup.node.config.cjs');
    }

    protected compileUserRollupConfig(): string {
        return `/**
 * This file can be edited to customize rollup configuration.
 * To reset delete this file and rerun theia build again.
 */
// @ts-check
const configs = require('./gen-rollup.config.cjs');
${this.ifBrowserOnly('', `const nodeConfig = require('./gen-rollup.node.config.cjs');`)}

module.exports = [
    ...configs${this.ifBrowserOnly('', ',\n    nodeConfig')}
];
`;
    }

    protected compileRollupConfig(): string {
        const outputPath = `path.resolve(__dirname, 'lib', 'frontend')`;
        //const mode = `process.env.NODE_ENV === 'production' ? 'production' : 'development'`;
        const isProduction = `process.env.NODE_ENV === 'production'`;

        return `/**
 * Don't touch this file. It will be regenerated by theia build.
 * To customize rollup configuration change ${this.configPath}
 */
// @ts-check
const path = require('path');
const resolvePackagePath = require('resolve-package-path');
const { nodeResolve } = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const { terser } = require('@rollup/plugin-terser');
const postcss = require('rollup-plugin-postcss');
const copy = require('rollup-plugin-copy');
const replace = require('@rollup/plugin-replace');
const json = require('@rollup/plugin-json');
const alias = require('@rollup/plugin-alias');

const outputPath = ${outputPath};
const isProduction = ${isProduction};

// Custom resolveId hook to resolve modules from workspace root
const workspaceRoot = path.resolve(__dirname, '../..');
const resolveFromWorkspace = {
    name: 'resolve-from-workspace',
    resolveId(id, importer) {
        // Only handle bare module specifiers (not relative paths)
        if (id.startsWith('.') || id.startsWith('/') || path.isAbsolute(id)) {
            return null; // Let other plugins handle it
        }
        
        // Strip query strings like ?commonjs-external
        const originalId = id;
        const queryIndex = id.indexOf('?');
        if (queryIndex !== -1) {
            id = id.substring(0, queryIndex);
        }
        
        // Node.js built-ins should be external for browser builds
        const nodeBuiltins = ['perf_hooks', 'fs', 'path', 'os', 'crypto', 'stream', 'util', 'events', 'buffer', 'url', 'http', 'https', 'net', 'tls', 'zlib', 'child_process', 'cluster', 'dgram', 'dns', 'readline', 'repl', 'string_decoder', 'tty', 'vm', 'worker_threads'];
        if (nodeBuiltins.includes(id)) {
            return null; // Let node-resolve mark it as external
        }
        
        const fs = require('fs');
        
        // Handle subpath imports like @theia/core/shared/inversify
        if (id.startsWith('@theia/')) {
            const parts = id.split('/');
            const packageName = parts.slice(0, 2).join('/'); // @theia/core
            const subpath = parts.slice(2).join('/'); // shared/inversify
            
            // Helper function to check if path is a directory and resolve index.js
            const resolveDirectory = (dirPath) => {
                try {
                    if (fs.existsSync(dirPath)) {
                        const stat = fs.statSync(dirPath);
                        if (stat.isDirectory()) {
                            const indexFile = path.join(dirPath, 'index.js');
                            if (fs.existsSync(indexFile)) {
                                return indexFile;
                            }
                        }
                    }
                } catch (e) {
                    // Ignore errors
                }
                return null;
            };
            
            // Try workspace root node_modules first
            const nodeModulesPath = path.join(workspaceRoot, 'node_modules', packageName);
            if (fs.existsSync(nodeModulesPath)) {
                if (subpath) {
                    // Try direct file path
                    const subpathFile = path.join(nodeModulesPath, subpath + '.js');
                    if (fs.existsSync(subpathFile) && fs.statSync(subpathFile).isFile()) {
                        return subpathFile;
                    }
                    // Try as directory with index.js
                    const subpathDir = path.join(nodeModulesPath, subpath);
                    const dirIndex = resolveDirectory(subpathDir);
                    if (dirIndex) {
                        return dirIndex;
                    }
                    // Try lib subpath only if subpath doesn't already start with lib/
                    if (!subpath.startsWith('lib/')) {
                        const libSubpath = path.join(nodeModulesPath, 'lib', subpath + '.js');
                        if (fs.existsSync(libSubpath) && fs.statSync(libSubpath).isFile()) {
                            return libSubpath;
                        }
                        // Try lib subpath as directory
                        const libSubpathDir = path.join(nodeModulesPath, 'lib', subpath);
                        const libDirIndex = resolveDirectory(libSubpathDir);
                        if (libDirIndex) {
                            return libDirIndex;
                        }
                    }
                } else {
                    // No subpath, resolve main entry
                    const pkgPath = path.join(nodeModulesPath, 'package.json');
                    if (fs.existsSync(pkgPath)) {
                        const pkg = require(pkgPath);
                        const main = pkg.main || pkg.module || 'lib/index.js';
                        return path.resolve(nodeModulesPath, main);
                    }
                }
            }
            
            // Try packages directory
            const packageNameOnly = parts[1]; // core
            const packagePath = path.join(workspaceRoot, 'packages', packageNameOnly);
            if (fs.existsSync(packagePath)) {
                if (subpath) {
                    // Try direct file path
                    const subpathFile = path.join(packagePath, subpath + '.js');
                    if (fs.existsSync(subpathFile) && fs.statSync(subpathFile).isFile()) {
                        return subpathFile;
                    }
                    // Try as directory with index.js
                    const subpathDir = path.join(packagePath, subpath);
                    const dirIndex = resolveDirectory(subpathDir);
                    if (dirIndex) {
                        return dirIndex;
                    }
                    // Try lib subpath only if subpath doesn't already start with lib/
                    if (!subpath.startsWith('lib/')) {
                        const libSubpath = path.join(packagePath, 'lib', subpath + '.js');
                        if (fs.existsSync(libSubpath) && fs.statSync(libSubpath).isFile()) {
                            return libSubpath;
                        }
                        // Try lib subpath as directory
                        const libSubpathDir = path.join(packagePath, 'lib', subpath);
                        const libDirIndex = resolveDirectory(libSubpathDir);
                        if (libDirIndex) {
                            return libDirIndex;
                        }
                    }
                } else {
                    // No subpath, resolve main entry
                    const pkgPath = path.join(packagePath, 'package.json');
                    if (fs.existsSync(pkgPath)) {
                        const pkg = require(pkgPath);
                        const main = pkg.main || pkg.module || 'lib/index.js';
                        const resolved = path.resolve(packagePath, main);
                        if (fs.existsSync(resolved)) {
                            return resolved;
                        }
                        // If main doesn't have extension, try with .js
                        const resolvedWithExt = resolved + '.js';
                        if (fs.existsSync(resolvedWithExt)) {
                            return resolvedWithExt;
                        }
                    }
                }
            }
        }
        
        // Handle subpath imports for other packages (e.g., y-protocols/sync, lib0/encoding)
        const parts = id.split('/');
        if (parts.length > 1) {
            const packageName = parts[0];
            const subpath = parts.slice(1).join('/');
            
            // Try workspace root node_modules
            const nodeModulesPath = path.join(workspaceRoot, 'node_modules', packageName);
            if (fs.existsSync(nodeModulesPath)) {
                // Helper function to check if path is a directory and resolve index.js
                const resolveDirectory = (dirPath) => {
                    try {
                        if (fs.existsSync(dirPath)) {
                            const stat = fs.statSync(dirPath);
                            if (stat.isDirectory()) {
                                const indexFile = path.join(dirPath, 'index.js');
                                if (fs.existsSync(indexFile)) {
                                    return indexFile;
                                }
                            }
                        }
                    } catch (e) {
                        // Ignore errors
                    }
                    return null;
                };
                
                // Try subpath as file
                const subpathFile = path.join(nodeModulesPath, subpath + '.js');
                if (fs.existsSync(subpathFile) && fs.statSync(subpathFile).isFile()) {
                    return subpathFile;
                }
                // Try subpath as directory
                const subpathDir = path.join(nodeModulesPath, subpath);
                const dirIndex = resolveDirectory(subpathDir);
                if (dirIndex) {
                    return dirIndex;
                }
                // Try package exports if available
                const pkgPath = path.join(nodeModulesPath, 'package.json');
                if (fs.existsSync(pkgPath)) {
                    try {
                        const pkg = require(pkgPath);
                        // Check package.json exports field for subpath
                        if (pkg.exports) {
                            const exportPath = pkg.exports['./' + subpath] || pkg.exports['./' + subpath + '.js'];
                            if (exportPath) {
                                const resolved = path.resolve(nodeModulesPath, typeof exportPath === 'string' ? exportPath : (exportPath.default || exportPath.browser || exportPath.module));
                                if (fs.existsSync(resolved)) {
                                    return resolved;
                                }
                            }
                        }
                    } catch (e) {
                        // Ignore errors
                    }
                }
            }
        }
        
        // Try to resolve from workspace root node_modules for other packages
        const workspaceNodeModules = path.join(workspaceRoot, 'node_modules', id);
        const possiblePaths = [
            workspaceNodeModules,
            path.join(workspaceNodeModules, 'index.js'),
            path.join(workspaceNodeModules, 'package.json')
        ];
        
        for (const possiblePath of possiblePaths) {
            try {
                if (fs.existsSync(possiblePath)) {
                    if (possiblePath.endsWith('package.json')) {
                        const pkg = require(possiblePath);
                        let mainPath;
                        // Check exports field first (ESM packages)
                        if (pkg.exports) {
                            const defaultExport = pkg.exports['.'] || pkg.exports['./'] || pkg.exports.default;
                            if (defaultExport) {
                                const exportPath = typeof defaultExport === 'string' ? defaultExport : (defaultExport.default || defaultExport.browser || defaultExport.module);
                                if (exportPath) {
                                    mainPath = path.resolve(path.dirname(possiblePath), exportPath);
                                    if (fs.existsSync(mainPath)) {
                                        return mainPath;
                                    }
                                }
                            }
                        }
                        // Fall back to main/module fields
                        const main = pkg.main || pkg.module || 'index.js';
                        mainPath = path.resolve(path.dirname(possiblePath), main);
                        // If main doesn't have extension, try with .js
                        if (!fs.existsSync(mainPath)) {
                            const mainWithExt = mainPath + '.js';
                            if (fs.existsSync(mainWithExt)) {
                                return mainWithExt;
                            }
                        }
                        return mainPath;
                    }
                    if (fs.statSync(possiblePath).isFile()) {
                        return possiblePath;
                    }
                }
            } catch (e) {
                // Continue to next path
            }
        }
        
        return null; // Let node-resolve handle it
    }
};

const plugins = [
    alias({
        entries: [
            { find: 'path', replacement: require.resolve('path-browserify') }
        ]
    }),
    replace({
        'process.env.NODE_ENV': JSON.stringify(isProduction ? 'production' : 'development'),
        preventAssignment: true
    }),
    resolveFromWorkspace,
    nodeResolve({
        browser: ${this.pck.isElectron() ? 'false' : 'true'},
        preferBuiltins: ${this.pck.isElectron() ? 'true' : 'false'},
        extensions: ['.js', '.json'],
        // Resolve all modules, don't skip any
        skip: [],
        // Resolve from workspace root for both browser and Electron
        rootDir: path.resolve(__dirname, '../..'),
        // Don't mark any modules as external - let commonjs plugin handle them
        exportConditions: ${this.pck.isElectron() ? `['node', 'default']` : `['browser', 'default']`}
    }),
    commonjs({
        transformMixedEsModules: true,
        requireReturnsDefault: 'auto',
        // Entry files are now ESM, but dependencies may still be CommonJS
        include: ['**/node_modules/**/*.js'],
        exclude: ['**/src-gen/**/*.js'],
        // Don't treat any modules as external - bundle everything
        ignore: [],
        // Don't create external parameters - bundle everything
        strictRequires: false,
        // Ensure all requires are transformed, not externalized
        defaultIsModuleExports: 'auto'
    }),
    json(),
    postcss({
        extract: false,
        inject: true,
        minimize: isProduction,
        sourceMap: true
    }),
    // Handle WASM files as assets - copy them to output and return URL
    {
        name: 'wasm-loader',
        load(id) {
            if (id.endsWith('.wasm')) {
                const fs = require('fs');
                const path = require('path');
                // Copy WASM file to output directory
                const wasmFileName = path.basename(id);
                const wasmOutputPath = path.join(outputPath, wasmFileName);
                try {
                    fs.copyFileSync(id, wasmOutputPath);
                } catch (e) {
                    // Ignore if already exists or other errors
                }
                // Return code that loads the WASM file from the output directory
                const relativePath = path.relative(outputPath, wasmOutputPath).replace(/\\\\/g, '/');
                return \`export default '\${relativePath}';\`;
            }
            return null;
        }
    },
    // TypeScript plugin removed - TypeScript files are already compiled to JavaScript
    // by tsc before this build step. Rollup processes the compiled .js files.
    copy({
        targets: [
            {
                src: path.resolve(__dirname, 'src-gen/frontend/secondary-window.html'),
                dest: outputPath
            }${this.ifPackage('@theia/plugin-ext', `,
            {
                src: path.join(resolvePackagePath('@theia/plugin-ext', __dirname), '..', 'src', 'main', 'browser', 'webview', 'pre'),
                dest: path.resolve(__dirname, 'lib', 'webview', 'pre')
            }`)}${this.ifPackage('@theia/plugin-ext-vscode', `,
            {
                src: path.join(resolvePackagePath('@theia/plugin-ext-vscode', __dirname), '..', 'lib', 'node', 'context', 'plugin-vscode-init-fe.js'),
                dest: path.resolve(__dirname, 'lib', 'frontend', 'context', 'plugin-vscode-init-fe.js')
            }`)}
        ]
    })
];

if (isProduction) {
    plugins.push(terser({
        sourcemap: true,
        compress: {
            drop_console: false
        }
    }));
}

// Preload bundle config for electron (only added if preload.js exists)
const preloadConfig = (() => {
    try {
        const fs = require('fs');
        const preloadPath = path.resolve(__dirname, 'src-gen/frontend/preload.js');
        if (fs.existsSync(preloadPath)) {
            return {
                input: preloadPath,
                output: {
                    file: path.join(outputPath, 'preload.js'),
                    format: 'es',
                    sourcemap: true
                },
                plugins: [
                    nodeResolve({
                        browser: false,
                        preferBuiltins: true,
                        extensions: ['.js', '.json'],
                        // Resolve all modules, don't skip any
                        skip: [],
                        // Don't mark any modules as external - let commonjs plugin handle them
                        exportConditions: ['node', 'default']
                    }),
                    commonjs({
                        transformMixedEsModules: true,
                        requireReturnsDefault: 'auto'
                    }),
                    json()
                ],
                // For Electron preload bundle, don't externalize anything - bundle everything
                // Node.js built-ins and electron will be handled by the commonjs plugin
                external: [],
                onwarn(warning, warn) {
                    if (warning.code === 'SOURCEMAP_ERROR') return;
                    warn(warning);
                }
            };
        }
    } catch (e) {
        // preload.js doesn't exist or fs is not available (browser-only build)
    }
    return null;
})();

const configs = [
    {
        input: path.resolve(__dirname, 'src-gen/frontend/index.js'),
        output: {
            file: path.join(outputPath, 'bundle.js'),
            format: 'es',
            sourcemap: true,
            inlineDynamicImports: true
        },
        plugins: [
            ...plugins
        ],
        // For Electron frontend bundle, don't externalize anything - bundle everything
        // Node.js built-ins will be handled by the commonjs plugin
        external: [],
        onwarn(warning, warn) {
            // Ignore source map warnings
            if (warning.code === 'SOURCEMAP_ERROR') return;
            // Ignore Monaco require warnings
            if (warning.message && warning.message.includes('require')) return;
            warn(warning);
        }
    }${this.ifMonaco(() => `,
    {
        input: (() => {
            // Resolve Monaco worker path at runtime
            // Check workspace locations: root node_modules, packages/*/node_modules
            const resolvePackagePath = require('resolve-package-path');
            const fs = require('fs');
            const path = require('path');
            
            let monacoCorePath = resolvePackagePath('@theia/monaco-editor-core', __dirname);
            
            // If not found, try workspace locations
            if (!monacoCorePath) {
                const workspaceRoot = path.resolve(__dirname, '../..');
                const possiblePaths = [
                    path.join(workspaceRoot, 'node_modules', '@theia', 'monaco-editor-core', 'package.json'),
                    path.join(workspaceRoot, 'packages', 'monaco', 'node_modules', '@theia', 'monaco-editor-core', 'package.json'),
                    path.join(workspaceRoot, 'packages', 'ai-core', 'node_modules', '@theia', 'monaco-editor-core', 'package.json')
                ];
                
                for (const possiblePath of possiblePaths) {
                    if (fs.existsSync(possiblePath)) {
                        monacoCorePath = possiblePath;
                        break;
                    }
                }
            }
            
            if (!monacoCorePath) {
                throw new Error('Could not resolve @theia/monaco-editor-core package. Make sure it is installed.');
            }
            return path.join(path.dirname(monacoCorePath), 'esm', 'vs', 'editor', 'editor.worker.js');
        })(),
        output: {
            file: path.join(outputPath, 'editor.worker.js'),
            format: 'es',
            sourcemap: true
        },
        plugins: [
            nodeResolve({
                browser: true,
                preferBuiltins: false,
                extensions: ['.js', '.json']
            }),
            commonjs({
                transformMixedEsModules: true,
                requireReturnsDefault: 'auto'
            })
            // TypeScript plugin removed - Monaco worker is already compiled JavaScript
        ],
        onwarn(warning, warn) {
            if (warning.code === 'SOURCEMAP_ERROR') return;
            warn(warning);
        }
    }`)}
];

// Add preload config if it exists and is not null
if (preloadConfig) {
    configs.push(preloadConfig);
}

module.exports = configs;
`;
    }

    protected compileNodeRollupConfig(): string {
        return `/**
 * Don't touch this file. It will be regenerated by theia build.
 * To customize rollup configuration change ${this.configPath}
 */
// @ts-check
const path = require('path');
const { nodeResolve } = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const json = require('@rollup/plugin-json');

const outputPath = path.resolve(__dirname, 'lib', 'backend');

// Plugin to add .js extensions to @theia/ imports
const addJsExtension = {
    name: 'add-js-extension',
    renderChunk(code) {
        // Add .js extension to @theia/ package imports that don't already have an extension
        const importRegex = /import\\s+.*?\\s+from\\s+['"]([^'"]+)['"]/g;
        let modifiedCode = code;
        let match;
        
        while ((match = importRegex.exec(code)) !== null) {
            const importPath = match[1];
            // Only process @theia/ package imports
            if (importPath.startsWith('@theia/')) {
                // Skip if it already has an extension
                if (!importPath.match(/\\.(js|json|mjs|ts|tsx)$/)) {
                    const newImportPath = importPath + '.js';
                    modifiedCode = modifiedCode.replace(match[0], match[0].replace(importPath, newImportPath));
                }
            }
        }
        
        return { code: modifiedCode, map: null };
    }
};

const config = {
    input: path.resolve(__dirname, 'src-gen/backend/main.js'),
    output: {
        file: path.join(outputPath, 'main.js'),
        format: 'es',
        sourcemap: true
    },
    external: (id) => {
        // Don't bundle node built-ins or dependencies
        if (id.startsWith('node:') || !id.startsWith('.') && !path.isAbsolute(id)) {
            return true;
        }
        return false;
    },
    plugins: [
        nodeResolve({
            preferBuiltins: true,
            extensions: ['.js', '.json']
        }),
        commonjs(),
        json(),
        addJsExtension
        // TypeScript plugin removed - TypeScript files are already compiled to JavaScript
        // by tsc before this build step. Rollup processes the compiled .js files.
    ],
    onwarn(warning, warn) {
        if (warning.code === 'SOURCEMAP_ERROR') return;
        warn(warning);
    }
};

module.exports = config;
`;
    }

}
