/**
 * Don't touch this file. It will be regenerated by theia build.
 * To customize rollup configuration change C:\Users\frank_lemanschik\isomorphic-git\isomorphic-git\universal-git\worktrees\theia\examples\electron\rollup.config.js
 */
// @ts-check
const path = require('path');
const resolvePackagePath = require('resolve-package-path');
const { nodeResolve } = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const { terser } = require('@rollup/plugin-terser');
const postcss = require('rollup-plugin-postcss');
const copy = require('rollup-plugin-copy');
const replace = require('@rollup/plugin-replace');
const json = require('@rollup/plugin-json');
const alias = require('@rollup/plugin-alias');

const outputPath = path.resolve(__dirname, 'lib', 'frontend');
const isProduction = process.env.NODE_ENV === 'production';

// Custom resolveId hook to resolve modules from workspace root
const workspaceRoot = path.resolve(__dirname, '../..');
const resolveFromWorkspace = {
    name: 'resolve-from-workspace',
    resolveId(id, importer) {
        // Only handle bare module specifiers (not relative paths)
        if (id.startsWith('.') || id.startsWith('/') || path.isAbsolute(id)) {
            return null; // Let other plugins handle it
        }
        
        const fs = require('fs');
        
        // Handle subpath imports like @theia/core/shared/inversify
        if (id.startsWith('@theia/')) {
            const parts = id.split('/');
            const packageName = parts.slice(0, 2).join('/'); // @theia/core
            const subpath = parts.slice(2).join('/'); // shared/inversify
            
            // Try workspace root node_modules first
            const nodeModulesPath = path.join(workspaceRoot, 'node_modules', packageName);
            if (fs.existsSync(nodeModulesPath)) {
                if (subpath) {
                    // Try direct file path
                    const subpathFile = path.join(nodeModulesPath, subpath + '.js');
                    if (fs.existsSync(subpathFile)) {
                        return subpathFile;
                    }
                    // Try lib subpath
                    const libSubpath = path.join(nodeModulesPath, 'lib', subpath + '.js');
                    if (fs.existsSync(libSubpath)) {
                        return libSubpath;
                    }
                } else {
                    // No subpath, resolve main entry
                    const pkgPath = path.join(nodeModulesPath, 'package.json');
                    if (fs.existsSync(pkgPath)) {
                        const pkg = require(pkgPath);
                        const main = pkg.main || pkg.module || 'lib/index.js';
                        return path.resolve(nodeModulesPath, main);
                    }
                }
            }
            
            // Try packages directory
            const packageNameOnly = parts[1]; // core
            const packagePath = path.join(workspaceRoot, 'packages', packageNameOnly);
            if (fs.existsSync(packagePath)) {
                if (subpath) {
                    // Try direct file path
                    const subpathFile = path.join(packagePath, subpath + '.js');
                    if (fs.existsSync(subpathFile)) {
                        return subpathFile;
                    }
                    // Try lib subpath
                    const libSubpath = path.join(packagePath, 'lib', subpath + '.js');
                    if (fs.existsSync(libSubpath)) {
                        return libSubpath;
                    }
                } else {
                    // No subpath, resolve main entry
                    const pkgPath = path.join(packagePath, 'package.json');
                    if (fs.existsSync(pkgPath)) {
                        const pkg = require(pkgPath);
                        const main = pkg.main || pkg.module || 'lib/index.js';
                        const resolved = path.resolve(packagePath, main);
                        if (fs.existsSync(resolved)) {
                            return resolved;
                        }
                    }
                }
            }
        }
        
        // Try to resolve from workspace root node_modules for other packages
        const workspaceNodeModules = path.join(workspaceRoot, 'node_modules', id);
        const possiblePaths = [
            workspaceNodeModules,
            path.join(workspaceNodeModules, 'index.js'),
            path.join(workspaceNodeModules, 'package.json')
        ];
        
        for (const possiblePath of possiblePaths) {
            try {
                if (fs.existsSync(possiblePath)) {
                    if (possiblePath.endsWith('package.json')) {
                        const pkg = require(possiblePath);
                        const main = pkg.main || pkg.module || 'index.js';
                        return path.resolve(path.dirname(possiblePath), main);
                    }
                    if (fs.statSync(possiblePath).isFile()) {
                        return possiblePath;
                    }
                }
            } catch (e) {
                // Continue to next path
            }
        }
        
        return null; // Let node-resolve handle it
    }
};

const plugins = [
    alias({
        entries: [
            { find: 'path', replacement: require.resolve('path-browserify') }
        ]
    }),
    replace({
        'process.env.NODE_ENV': JSON.stringify(isProduction ? 'production' : 'development'),
        preventAssignment: true
    }),
    resolveFromWorkspace,
    nodeResolve({
        browser: false,
        preferBuiltins: true,
        extensions: ['.js', '.json'],
        // Resolve all modules, don't skip any
        skip: [],
        // Resolve from workspace root for both browser and Electron
        rootDir: path.resolve(__dirname, '../..'),
        // Don't mark any modules as external - let commonjs plugin handle them
        exportConditions: ['node', 'default']
    }),
    commonjs({
        transformMixedEsModules: true,
        requireReturnsDefault: 'auto',
        // Entry files are now ESM, but dependencies may still be CommonJS
        include: ['**/node_modules/**/*.js'],
        exclude: ['**/src-gen/**/*.js'],
        // Don't treat any modules as external - bundle everything
        ignore: [],
        // Don't create external parameters - bundle everything
        strictRequires: false,
        // Ensure all requires are transformed, not externalized
        defaultIsModuleExports: 'auto'
    }),
    json(),
    postcss({
        extract: false,
        inject: true,
        minimize: isProduction,
        sourceMap: true
    }),
    // TypeScript plugin removed - TypeScript files are already compiled to JavaScript
    // by tsc before this build step. Rollup processes the compiled .js files.
    copy({
        targets: [
            {
                src: path.resolve(__dirname, 'src-gen/frontend/secondary-window.html'),
                dest: outputPath
            },
            {
                src: path.join(resolvePackagePath('@theia/plugin-ext', __dirname), '..', 'src', 'main', 'browser', 'webview', 'pre'),
                dest: path.resolve(__dirname, 'lib', 'webview', 'pre')
            },
            {
                src: path.join(resolvePackagePath('@theia/plugin-ext-vscode', __dirname), '..', 'lib', 'node', 'context', 'plugin-vscode-init-fe.js'),
                dest: path.resolve(__dirname, 'lib', 'frontend', 'context', 'plugin-vscode-init-fe.js')
            }
        ]
    })
];

if (isProduction) {
    plugins.push(terser({
        sourcemap: true,
        compress: {
            drop_console: false
        }
    }));
}

// Preload bundle config for electron (only added if preload.js exists)
const preloadConfig = (() => {
    try {
        const fs = require('fs');
        const preloadPath = path.resolve(__dirname, 'src-gen/frontend/preload.js');
        if (fs.existsSync(preloadPath)) {
            return {
                input: preloadPath,
                output: {
                    file: path.join(outputPath, 'preload.js'),
                    format: 'iife',
                    name: 'TheiaPreload',
                    sourcemap: true
                },
                plugins: [
                    nodeResolve({
                        browser: false,
                        preferBuiltins: true,
                        extensions: ['.js', '.json'],
                        // Resolve all modules, don't skip any
                        skip: [],
                        // Don't mark any modules as external - let commonjs plugin handle them
                        exportConditions: ['node', 'default']
                    }),
                    commonjs({
                        transformMixedEsModules: true,
                        requireReturnsDefault: 'auto'
                    }),
                    json()
                ],
                // For Electron preload bundle, don't externalize anything - bundle everything
                // Node.js built-ins and electron will be handled by the commonjs plugin
                external: [],
                onwarn(warning, warn) {
                    if (warning.code === 'SOURCEMAP_ERROR') return;
                    warn(warning);
                }
            };
        }
    } catch (e) {
        // preload.js doesn't exist or fs is not available (browser-only build)
    }
    return null;
})();

const configs = [
    {
        input: path.resolve(__dirname, 'src-gen/frontend/index.js'),
        output: {
            file: path.join(outputPath, 'bundle.js'),
            format: 'iife',
            name: 'Theia',
            sourcemap: true,
            globals: {}
        },
        plugins: [
            ...plugins
        ],
        // For Electron frontend bundle, don't externalize anything - bundle everything
        // Node.js built-ins will be handled by the commonjs plugin
        external: [],
        onwarn(warning, warn) {
            // Ignore source map warnings
            if (warning.code === 'SOURCEMAP_ERROR') return;
            // Ignore Monaco require warnings
            if (warning.message && warning.message.includes('require')) return;
            warn(warning);
        }
    },
    {
        input: (() => {
            // Resolve Monaco worker path at runtime
            // Check workspace locations: root node_modules, packages/*/node_modules
            const resolvePackagePath = require('resolve-package-path');
            const fs = require('fs');
            const path = require('path');
            
            let monacoCorePath = resolvePackagePath('@theia/monaco-editor-core', __dirname);
            
            // If not found, try workspace locations
            if (!monacoCorePath) {
                const workspaceRoot = path.resolve(__dirname, '../..');
                const possiblePaths = [
                    path.join(workspaceRoot, 'node_modules', '@theia', 'monaco-editor-core', 'package.json'),
                    path.join(workspaceRoot, 'packages', 'monaco', 'node_modules', '@theia', 'monaco-editor-core', 'package.json'),
                    path.join(workspaceRoot, 'packages', 'ai-core', 'node_modules', '@theia', 'monaco-editor-core', 'package.json')
                ];
                
                for (const possiblePath of possiblePaths) {
                    if (fs.existsSync(possiblePath)) {
                        monacoCorePath = possiblePath;
                        break;
                    }
                }
            }
            
            if (!monacoCorePath) {
                throw new Error('Could not resolve @theia/monaco-editor-core package. Make sure it is installed.');
            }
            return path.join(path.dirname(monacoCorePath), 'esm', 'vs', 'editor', 'editor.worker.js');
        })(),
        output: {
            file: path.join(outputPath, 'editor.worker.js'),
            format: 'iife',
            name: 'EditorWorker',
            sourcemap: true
        },
        plugins: [
            nodeResolve({
                browser: true,
                preferBuiltins: false,
                extensions: ['.js', '.json']
            }),
            commonjs({
                transformMixedEsModules: true,
                requireReturnsDefault: 'auto'
            })
            // TypeScript plugin removed - Monaco worker is already compiled JavaScript
        ],
        onwarn(warning, warn) {
            if (warning.code === 'SOURCEMAP_ERROR') return;
            warn(warning);
        }
    }
];

// Add preload config if it exists and is not null
if (preloadConfig) {
    configs.push(preloadConfig);
}

module.exports = configs;
