/**
 * Don't touch this file. It will be regenerated by theia build.
 * To customize rollup configuration change C:\Users\frank_lemanschik\isomorphic-git\isomorphic-git\universal-git\worktrees\theia\examples\electron\rollup.config.js
 */
// @ts-check
const path = require('path');
const { nodeResolve } = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const json = require('@rollup/plugin-json');

const outputPath = path.resolve(__dirname, 'lib', 'backend');

const config = {
    input: path.resolve(__dirname, 'src-gen/backend/main.js'),
    output: {
        file: path.join(outputPath, 'main.js'),
        format: 'cjs',
        sourcemap: true
    },
    external: (id) => {
        // Don't bundle node built-ins or dependencies
        if (id.startsWith('node:') || !id.startsWith('.') && !path.isAbsolute(id)) {
            return true;
        }
        return false;
    },
    plugins: [
        nodeResolve({
            preferBuiltins: true,
            extensions: ['.js', '.json']
        }),
        commonjs(),
        json()
        // TypeScript plugin removed - TypeScript files are already compiled to JavaScript
        // by tsc before this build step. Rollup processes the compiled .js files.
    ],
    onwarn(warning, warn) {
        if (warning.code === 'SOURCEMAP_ERROR') return;
        warn(warning);
    }
};

module.exports = config;
